In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [2]:
orders = pd.read_excel(
    r"E:\CODING_ALL\Data Analytics\projrcts\RetailIQ\data\processed\order_items.xlsx",
    sheet_name="processed"
)

df = orders.copy()

In [3]:
print("Rows and columns:", df.shape)

display(df.head())

Rows and columns: (397569, 12)

,order_id,product_id,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
0,ORD-301242,PROD-000738,2,244.40,0.339607,166.00,488.80,22.60,6.48,351.88,173.28,172.12
1,ORD-301242,PROD-000181,3,287.13,0.362076,311.89,861.39,38.47,5.55,593.52,415.05,172.92
2,ORD-773460,PROD-000973,4,754.80,0.468300,1413.89,3019.20,305.01,9.00,1919.32,1976.16,-65.84
3,ORD-773460,PROD-000268,4,31.36,0.336182,42.17,125.44,15.82,0.00,99.09,55.72,43.37
4,ORD-449374,PROD-001040,3,6.31,0.089678,1.70,18.93,1.21,0.98,19.42,5.91,12.53

# Order Items Data Exploration and Cleaning

## 1. Dataset Overview

In [4]:
# Dataset overview
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

display(df.head())

print("\nData types:")
df.info()

Shape: (397569, 12)
Columns: ['order_id', 'product_id', 'quantity', 'unit_price', 'discount_percentage', 'discount_amount', 'gross_sales', 'tax_amount', 'shipping_cost', 'net_sales', 'product_cost', 'profit']

,order_id,product_id,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
0,ORD-301242,PROD-000738,2,244.40,0.339607,166.00,488.80,22.60,6.48,351.88,173.28,172.12
1,ORD-301242,PROD-000181,3,287.13,0.362076,311.89,861.39,38.47,5.55,593.52,415.05,172.92
2,ORD-773460,PROD-000973,4,754.80,0.468300,1413.89,3019.20,305.01,9.00,1919.32,1976.16,-65.84
3,ORD-773460,PROD-000268,4,31.36,0.336182,42.17,125.44,15.82,0.00,99.09,55.72,43.37
4,ORD-449374,PROD-001040,3,6.31,0.089678,1.70,18.93,1.21,0.98,19.42,5.91,12.53

Data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397569 entries, 0 to 397568
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             397569 non-null  object
 1   product_id           397569 non-null  object
 2   quantity             397569 non-null  int64
 3   unit_price           397569 non-null  float64
 4   discount_percentage  397569 non-null  float64
 5   discount_amount      397569 non-null  float64
 6   gross_sales          397569 non-null  float64
 7   tax_amount           397569 non-null  float64
 8   shipping_cost        397569 non-null  float64
 9   net_sales            397569 non-null  float64
 10  product_cost         397569 non-null  float64
 11  profit               397569 non-null  float64
dtypes: float64(9), int64(1), object(2)
memory usage: 36.4+ MB

## 2. Statistical Analysis

In [5]:
# Statistical summary
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,397569,138116,ORD-688687,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_id,397569,1175,PROD-000839,414,NaN,NaN,NaN,NaN,NaN,NaN,NaN
quantity,397569.0,NaN,NaN,NaN,2.118792,1.196276,1.0,1.0,2.0,3.0,5.0
unit_price,397569.0,NaN,NaN,NaN,245.189134,251.035134,6.31,74.36,164.97,310.79,1482.95
discount_percentage,397569.0,NaN,NaN,NaN,0.147059,0.129986,0.0,0.048137,0.124253,0.199499,0.6
discount_amount,397569.0,NaN,NaN,NaN,89.667873,190.637796,0.0,5.94,26.34,86.03,3857.67
gross_sales,397569.0,NaN,NaN,NaN,519.01355,676.800478,6.31,122.0,280.19,643.56,7414.75
tax_amount,397569.0,NaN,NaN,NaN,46.183642,71.072019,0.26,9.56,22.55,52.34,1482.95
shipping_cost,397569.0,NaN,NaN,NaN,8.40901,6.777155,0.0,3.37,5.87,12.46,36.46
net_sales,397569.0,NaN,NaN,NaN,483.938328,615.430188,5.35,124.28,271.1,595.24,8897.7
product_cost,397569.0,NaN,NaN,NaN,267.520046,394.773555,1.97,52.96,127.1,314.31,4968.15
profit,397569.0,NaN,NaN,NaN,208.009273,266.477677,-1260.28,53.73,121.66,259.66,4045.1

## 3. Data Quality Analysis

In [6]:
# Missing values
missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().mean() * 100
    ).round(2)
})

display(
    missing_report.sort_values(
        "Missing_Percentage",
        ascending=False
    )
)

                     Missing_Count  Missing_Percentage
order_id                         0                 0.0
product_id                       0                 0.0
quantity                         0                 0.0
unit_price                       0                 0.0
discount_percentage              0                 0.0
discount_amount                  0                 0.0
gross_sales                      0                 0.0
tax_amount                       0                 0.0
shipping_cost                    0                 0.0
net_sales                        0                 0.0
product_cost                     0                 0.0
profit                           0                 0.0

In [7]:
# Duplicate analysis
print("Exact duplicate rows:", df.duplicated().sum())

Exact duplicate rows: 0

## 4. Data Cleaning

In [8]:
# Clean column names
df.columns = df.columns.str.strip()

# Clean text columns
text_cols = df.select_dtypes(
    include=["object", "string"]
).columns

for col in text_cols:
    df[col] = df[col].str.strip()
    df[col] = df[col].replace(
        r"^\s*$", np.nan, regex=True
    )

print("Basic text cleaning completed")

Basic text cleaning completed

In [9]:
print(df.columns.tolist())
print(df.select_dtypes(include="number").describe().T)

['order_id', 'product_id', 'quantity', 'unit_price', 'discount_percentage', 'discount_amount', 'gross_sales', 'tax_amount', 'shipping_cost', 'net_sales', 'product_cost', 'profit']
                        count        mean         std      min         25%  \
quantity             397569.0    2.118792    1.196276     1.00    1.000000
unit_price           397569.0  245.189134  251.035134     6.31   74.360000
discount_percentage  397569.0    0.147059    0.129986     0.00    0.048137
discount_amount      397569.0   89.667873  190.637796     0.00    5.940000
gross_sales          397569.0  519.013550  676.800478     6.31  122.000000
tax_amount           397569.0   46.183642   71.072019     0.26    9.560000
shipping_cost        397569.0    8.409010    6.777155     0.00    3.370000
net_sales            397569.0  483.938328  615.430188     5.35  124.280000
product_cost         397569.0  267.520046  394.773555     1.97   52.960000
profit               397569.0  208.009273  266.477677 -1260.28   53.730000

                            50%         75%      max
quantity               2.000000    3.000000     5.00
unit_price           164.970000  310.790000  1482.95
discount_percentage    0.124253    0.199499     0.60
discount_amount       26.340000   86.030000  3857.67
gross_sales          280.190000  643.560000  7414.75
tax_amount            22.550000   52.340000  1482.95
shipping_cost          5.870000   12.460000    36.46
net_sales            271.100000  595.240000  8897.70
product_cost         127.100000  314.310000  4968.15
profit               121.660000  259.660000  4045.10

In [10]:
numeric_cols = [
    "quantity",
    "unit_price",
    "discount_percentage",
    "discount_amount",
    "gross_sales",
    "tax_amount",
    "shipping_cost",
    "net_sales",
    "product_cost",
    "profit"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[numeric_cols].describe().T)

                        count        mean         std      min         25%  \
quantity             397569.0    2.118792    1.196276     1.00    1.000000
unit_price           397569.0  245.189134  251.035134     6.31   74.360000
discount_percentage  397569.0    0.147059    0.129986     0.00    0.048137
discount_amount      397569.0   89.667873  190.637796     0.00    5.940000
gross_sales          397569.0  519.013550  676.800478     6.31  122.000000
tax_amount           397569.0   46.183642   71.072019     0.26    9.560000
shipping_cost        397569.0    8.409010    6.777155     0.00    3.370000
net_sales            397569.0  483.938328  615.430188     5.35  124.280000
product_cost         397569.0  267.520046  394.773555     1.97   52.960000
profit               397569.0  208.009273  266.477677 -1260.28   53.730000

                            50%         75%      max
quantity               2.000000    3.000000     5.00
unit_price           164.970000  310.790000  1482.95
discount_percentage    0.124253    0.199499     0.60
discount_amount       26.340000   86.030000  3857.67
gross_sales          280.190000  643.560000  7414.75
tax_amount            22.550000   52.340000  1482.95
shipping_cost          5.870000   12.460000    36.46
net_sales            271.100000  595.240000  8897.70
product_cost         127.100000  314.310000  4968.15
profit               121.660000  259.660000  4045.10

## 5. Validation

In [11]:
print("Missing values:")
display(df.isnull().sum().to_frame("Missing_Count"))

print("Exact duplicate rows:", df.duplicated().sum())

print("Missing order IDs:", df["order_id"].isna().sum())
print("Missing product IDs:", df["product_id"].isna().sum())

Missing values:

                     Missing_Count
order_id                         0
product_id                       0
quantity                         0
unit_price                       0
discount_percentage              0
discount_amount                  0
gross_sales                      0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0

Exact duplicate rows: 0
Missing order IDs: 0
Missing product IDs: 0

In [12]:
checks = {
    "Quantity <= 0": df["quantity"] <= 0,
    "Negative unit price": df["unit_price"] < 0,
    "Discount percentage outside 0-100": (
        ~df["discount_percentage"].between(0, 100)
    ),
    "Negative discount amount": df["discount_amount"] < 0,
    "Negative gross sales": df["gross_sales"] < 0,
    "Negative tax": df["tax_amount"] < 0,
    "Negative shipping cost": df["shipping_cost"] < 0,
    "Negative product cost": df["product_cost"] < 0
}

for issue, condition in checks.items():
    print(f"{issue}: {condition.sum()}")

Quantity <= 0: 0
Negative unit price: 0
Discount percentage outside 0-100: 0
Negative discount amount: 0
Negative gross sales: 0
Negative tax: 0
Negative shipping cost: 0
Negative product cost: 0

In [13]:
df["expected_gross_sales"] = (
    df["quantity"] * df["unit_price"]
)

df["gross_sales_difference"] = (
    df["gross_sales"] - df["expected_gross_sales"]
)

display(
    df.loc[
        df["gross_sales_difference"].abs() > 0.02,
        [
            "order_id",
            "product_id",
            "quantity",
            "unit_price",
            "gross_sales",
            "expected_gross_sales",
            "gross_sales_difference"
        ]
    ].head(20)
)

Empty DataFrame
Columns: [order_id, product_id, quantity, unit_price, gross_sales, expected_gross_sales, gross_sales_difference]
Index: []


## 6. Export Cleaned Data

In [15]:
df.to_csv("cleaned_orders.csv", index=False)
print("Done!")

Done!